### ISSUE TITLE
Julia Computing Sunbird Install - Unable to find the new categories and term created

### ISSUE THREAD

**Issue by thillaibirla** [project-sunbird/sunbird-portal#277]
@kochhar @harishgilimi 

We had created a new set of categories for julia computing Sunbird install and the related terms for that.  While logged in as a content creator and trying to create a content or study material unable to find the new categories created, only the existing categories are shown.  We are able to find the new framework, category and term details when we use the search apis, but unable to see them when add
[AILP - Framework search.txt](https://github.com/project-sunbird/sunbird-portal/files/1776114/AILP.-.Framework.search.txt)
[AILP - Category search.txt](https://github.com/project-sunbird/sunbird-portal/files/1776115/AILP.-.Category.search.txt)

ing/inserting a content.  Can someone pls look into the issue.

Thanks,
Thillai.

**Comment by harishgilimi** [comment]
@thillaibirla Let me know the which version of sunbird portal is installed so that we can check

**Comment by thillaibirla** [comment]
@harishgilimi - 

ACTOR_SERVICE_VERSION=0.0.4-gold
PLAYER_VERSION=0.0.9-gold
CONTENT_SERVICE_VERSION=0.0.4-gold
LEARNER_SERVICE_VERSION=0.0.4-gold
PROXY_VERSION=0.0.1-gold

**Comment by harishgilimi** [comment]
@thillaibirla please add framework to the user  channel and it will work as we discussed and i am  closing this ticket

**Comment by thillaibirla** [comment]
@harishgilimi, still the issue persists.  the default root org for a new user is always stored as ORG_001 even the correct root org is provided in the API request.  After the creation of user, the root org for the user needs to be manually updated in the db for the workaround.  Can you pls suggest which version of the player service do we need to update it to?

**Comment by harishgilimi** [comment]
@thillaibirla  please take 0.0.10 gold version of player
