### ISSUE TITLE
Sunbird Julia instance - Unable to see the newly added framework while creating textbook

### ISSUE THREAD

**Issue by thillaibirla** [project-sunbird/sunbird-portal#295]
Hi Team, @harishgilimi 

We are unable to find the framework details which we created for Julia computing while creating a text book.  Last friday(16th March) after the hot fix it was working fine, but we tried checking today morning and its not working.  Am attaching the screenshots of inspect and the flow.  
[Julia Framework details missing.pdf](https://github.com/project-sunbird/sunbird-portal/files/1825359/Julia.Framework.details.missing.pdf)
Pls le me know if you need any other information.
Also we are unable to see any content added by us last week.

Thanks
Thillai.

**Comment by kochhar** [comment]
Cannot reproduce. @thillaibirla please follow the steps detailed in http://www.sunbird.org/contributions/filing_a_bug/ to file an appropriate bug report.
