### ISSUE TITLE
Need standalone Player Code 

### ISSUE THREAD

**Issue by sujeetkrjaiswal** [project-sunbird/sunbird-portal#36]
Since there is no comments in the code, and there is no independent document for the portal app, If you can help with the finding the player code, which as discussed should be independent and self sufficient.

Since I am exploring, it would be much helpful, if we can have a demo page, which just demonstrates the player, with some hard-coded .ekar file input.

I also tried to explore the mobile source code, as it also uses the web-view of android to load the content, but the entire js file was a bundle, and I was not able to extract the player code.

From my exploration till now, My understanding of player is that there is some bare-bone structure of player code, which downloads the renderer as well along with any other plugin file required.

Since I am planning to modify some of the features of the player, like menu etc. It would be of much help, if I can have access to some of the documentation of flow of data and function in the player.

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-commons #109](https://github.com/project-sunbird/sunbird-commons/issues/109) via [**ZenHub**](https://www.zenhub.com/)
