### ISSUE TITLE
#Bodhi Please provide the source code of the authoring tool

### ISSUE THREAD

**Issue by Anupama7879** [project-sunbird/sunbird-portal#65]
Please provide the source code of the authoring tool

**Comment by Anupama7879** [comment]
We haven't got your reply since 5 days. We need the source code for the bower components (collection-editor-iframe, content-editor-iframe and generic-editor-iframe) which are minified. We need it to customize the player and the authoring tool.

**Comment by kochhar** [comment]
@Anupama7879 noted. this is not yet an open-source component. will track this along with the request for the player code in https://github.com/project-sunbird/sunbird-portal/issues/65
